# Generated by Django 4.2.28 on 2026-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters from QR location'),
        ),
    ]
